### ============================================
### RAILWAY - Producción
### ============================================

### Obtener todos los admins (Railway)
GET https://oasisbackend-production-eb4d.up.railway.app/api/v1/admin
Accept: application/json

###

### Obtener un admin por su ID (Railway)
GET https://oasisbackend-production-eb4d.up.railway.app/api/v1/admin/11
Accept: application/json

###

### Login del administrador (Railway)
POST https://oasisbackend-production-eb4d.up.railway.app/api/v1/admin/login
Content-Type: application/json
Accept: application/json

{
  "correo": "camilo.mendez@tuguia.bo",
  "password": "luh123456789"
}

###

### ============================================
### LOCALHOST - Desarrollo Local
### ============================================

### Obtener todos los admins (Local)
GET http://localhost:9999/api/v1/admin
Accept: application/json

###

### Obtener un admin por su ID (Local)
GET http://localhost:9999/api/v1/admin/2
Accept: application/json

###

### Crear un nuevo admin (Local)
POST http://localhost:9999/api/v1/admin/create
Content-Type: application/json

{
  "correo": "manuel.delgadillo@tuguia.bo",
  "password": "Manu123456789.",
  "rol": {
    "idRol": 3
  },
  "persona": {
    "idPersona": 1
  }
}

###

### Login del administrador (Local)
POST http://localhost:9999/api/v1/admin/login
Content-Type: application/json
Accept: application/json

{
  "correo": "lu.huanca@tuguia.bo",
  "password": "luh123456789"
}

POST http://localhost:9999/api/v1/bloqueo/admin/11/desbloquear
Content-Type: application/json
Accept: application/json
{
  "motivo": "Actividad sospechosa detectada"
}

GET http://localhost:9999/api/v1/bloqueo/admin/11/info
Accept: application/json

{
}

### Actualizar un admin (Local)
PUT https://oasisbackend-production-eb4d.up.railway.app/api/v1/admin/update
Content-Type: application/json

{
  "idAdmin": 4,
  "correo": "camilo.mendez@tuguia.bo",
  "password": "luh12345678910",
  "rol": {
    "idRol": 5
  },
  "persona": {
    "idPersona": 4
  }
}

###

### Actualizar el rol de un admin (Railway)
PUT https://localhost:9999/api/v1/admin/updateRole/11
Content-Type: application/json

{
  "rolId": 3
}

###

### Actualizar el rol de un admin (Local)
PUT http://localhost:9999/api/v1/admin/updateRole/10
Content-Type: application/json

{
  "rolId": 3
}

###

### Eliminar un admin (Local)
DELETE http://localhost:9999/api/v1/admin/delete/
Accept: application/json
