### Obtener todos los admins
GET http://localhost:9999/api/v1/admin
Accept: application/json

###

### Obtener un admin por su ID
GET http://localhost:9999/api/v1/admin/4
Accept: application/json

###

### Crear un nuevo admin
POST http://localhost:9999/api/v1/admin/create
Content-Type: application/json

{
  "correo": "admin1@example.com",
  "password": "password1",
  "rol": {
    "idRol": 1
  },
  "persona": {
    "idPersona": 1
  }
}

###

### Login del administrador
POST http://localhost:9999/api/v1/admin/login
Content-Type: application/json
Accept: application/json

{
  "correo": "Luan.Huanca@oasis.bo",
  "password": "LuanH7303712"
}

###

### Actualizar un admin
PUT http://localhost:9999/api/v1/admin/update
Content-Type: application/json

{
  "idAdmin": 1,
  "correo": "admin1@example.com",
  "password": "newpassword1",
  "rol": {
    "idRol": 2
  },
  "persona": {
    "idPersona": 1
  }
}

###

### Actualizar el rol de un admin
PUT http://localhost:9999/api/v1/admin/updateRole/1
Content-Type: application/json

{
  "rolId": 9
}

###

### Eliminar un admin
DELETE http://localhost:9999/api/v1/admin/delete/4
Accept: application/json
