### Obtener todos los roles
GET http://localhost:9999/api/v1/rol
Accept: application/json

###

### Obtener un rol por ID
GET http://localhost:9999/api/v1/rol/1
Accept: application/json

###

### Crear un nuevo rol
POST http://localhost:9999/api/v1/rol/create
Content-Type: application/json

{
  "rol": "usuario2"
}

###

### Actualizar un rol
PUT http://localhost:9999/api/v1/rol/update
Content-Type: application/json

{
  "idRol": 2,
  "rol": "Tecnologia"
}

###

### Eliminar un rol
DELETE http://localhost:9999/api/v1/rol/delete/18
Accept: application/json