### Obtener todas las relaciones rol-permiso
GET http://localhost:9999/api/v1/rolpermiso
Accept: application/json

###

### Obtener una relación rol-permiso por ID
GET http://localhost:9999/api/v1/rolpermiso/1
Accept: application/json

###

### Crear una nueva relación rol-permiso
POST http://localhost:9999/api/v1/rolpermiso/create
Content-Type: application/json

{
  "idRol": 1,
  "idPermiso": 1
}

###

### Actualizar una relación rol-permiso
PUT http://localhost:9999/api/v1/rolpermiso/update
Content-Type: application/json

{
  "idRolPermiso": 1,
  "idRol": 1,
  "idPermiso": 2
}

###

### Eliminar una relación rol-permiso
DELETE http://localhost:9999/api/v1/rolpermiso/delete/1
Accept: application/json